" plugins
call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-unimpaired'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'mileszs/ack.vim'
Plug 'w0rp/ale'
Plug 'maralla/completor.vim'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeFind' }
Plug 'posva/vim-vue', { 'for': 'vue' }

call plug#end()

" eye candy
set background=dark
set hlsearch
set wildignore+=*.pyc,*/__pycache__,*/node_modules,*/htmlcov

" for quick movement
set relativenumber

" time-saver
set statusline=
set statusline+=[%n]\ %f
set statusline+=%=
set statusline+=[%{strlen(&fenc)?&fenc:&enc}%{&bomb?',BOM':''}]
set statusline+=[%{strlen(&ft)?&ft:'?'}]
set statusline+=[%{&fileformat}]
set statusline+=[%c%V,%l]
set statusline+=[%P]

" show possible mistakes
set listchars=tab:→\ ,trail:␣
set list
set colorcolumn=

" spaces matters
set shiftwidth=4
set softtabstop=4
set tabstop=4
set noexpandtab

" NERDTree
let NERDTreeRespectWildIgnore = 1
let NERDTreeQuitOnOpen = 1
map <C-n> :NERDTreeFind<CR>

" ale: visual config
let g:ale_lint_on_text_changed = 'never'

" ack.vim: use the silver searcher instead
let g:ackprg = 'ag --vimgrep'
